routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/////////////////////////////////////////////////////////////////////////////////////////////////

// AREA PUBBLICA
Route::prefix('/')->namespace('UI')->group(function () {
    Route::get('', 'BnbController@index')->name('welcome');
    Route::get('search', 'BnbController@search')->name('search');
    Route::get('apartments', 'BnbController@search')->name('ui.apartments.all');
    Route::get('apartments/{slug}', 'BnbController@show')->name('ui.apartments.show');
    Route::get('apartments/{slug}/message', 'BnbController@sendMessage')->name('ui.apartments.message');
});

Auth::routes();

/////////////////////////////////////////////////////////////////////////////////////////////////

// AREA PRIVATA
Route::prefix('admin')->name('admin.')->namespace('ADMIN')->middleware('auth')->group(function () {
    Route::resource('apartments', 'ApartmentController');
    Route::get('messages/delete/{id}', 'ApartmentController@destroyMessage');
    Route::get('apartments/{apartment}/messages', 'ApartmentController@messages')->name('apartments.messages');
});

Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');

/////////////////////////////////////////////////////////////////////////////////////////////////

// BRAINTREE - TRANSAZIONI

Route::prefix('/admin/')->namespace('Transactions')->group(function () {
    Route::get('apartments/{apartment}/payment', 'PaymentController@form')->name('payment.form');
    Route::get('apartments/payment/process', 'PaymentController@process')->name('payment.process');
    Route::get('apartments/{apartment}/payment/success', 'PaymentController@success')->name('payment.success');
    Route::get('apartments/{apartment}/payment/error', 'PaymentController@error')->name('payment.error');

});

/////////////////////////////////////////////////////////////////////////////////////////////////

app/Apartment.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class Apartment extends Model
{

    protected $guarded = ['services', 'sponsors'];

    // SERVICES
    public function services()
    {

        return $this->belongsToMany('App\Service');
    }

    // SPONSORS
    public function sponsors()
    {

        return $this->belongsToMany('App\Sponsor');
    }

    // MESSAGES
    public function messages()
    {

        return $this->hasMany('App\Message');
    }
     
    // USER
    public function user()
    {

        return $this->belongsTo('App\User');
    }

    public function views()
    {
        return $this->hasMany('App\View');
    }
}

app/Http/Controllers/ADMIN/ApartmentController.php
<?php

namespace App\Http\Controllers\ADMIN;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Apartment;
use App\Message;
use App\Service;
use App\Sponsor;
use App\View;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Auth;
use Carbon\Carbon;

class ApartmentController extends Controller
{

    protected $validation = [];

    public function __construct() {
        $this->validation = [
            'title' => 'required | string | max:100',
            'description' => 'required | string',
            'rooms' => 'required | numeric | max:127',
            'bathrooms' => 'required | numeric | max:4',
            'beds' => 'required | numeric | max:10',
            'mq' => 'required | numeric | max:300',
            'address' => 'required | string | max:100',
            'city' => 'required | string | max:50',
            'lat' => 'required | numeric | max:90 | min: -90',
            /*
            * -- Long max 180 da problemi--
            * 
            * Ho riscontrato il problema con queste coordinate (Lat: 44.427155, Long: 8.839384),
            * anche se la Long è meno di 180 mi resituisce un'errore dicendo che non piò inserire
            * una long maggiore di 180.
            * Quindi ho temporaneamente disabilitato max 180 per permettere il corretto inserimento del dato.
            * possibili solizioni:
            * - Validazione front-end e successivamente back-end
            */
           /**/ 'long' => 'required | numeric | min: -180', /**/ 

            'city' => 'required | string | max:50', 
            'image' => 'nullable|image|mimes:jpeg,png,jpg,gif,svg|max:2048',
            'visible' => 'boolean'
        ];
    } 

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $userId = Auth::id();
        $apartments = Apartment::where( 'user_id', $userId )->get();
        return view('admin.apartments.index', compact('apartments'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $services = Service::all();
        return view('admin.apartments.create', compact('services'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate( $this->validation );
        $data = $request->all();

        if ( isset($data['image']) ) {
            $data['image'] = Storage::disk('public')->put('images', $data['image']);
        }
        else{
            $data['image'] = "images/placeholder.png";
        }

        $data['user_id'] = Auth::id();

        $data['visible'] = !isset( $data['visible'] ) ? 0 : 1;

        // Generazione dello slug univoco
        do{
            $randomNumSlug = "-".rand(0, 100000000);
            $slugTmp = Str::slug( $data['title'], '-' ).$randomNumSlug;
        }
        while( Apartment::where('slug', $slugTmp)->first() );

        $data['slug'] = $slugTmp;

       $newapartment = Apartment::create( $data );

        if ( isset($data['services']) ) {
            $newapartment->services()->attach( $data['services'] );
        }

       return redirect()->route( 'admin.apartments.show', [ 'apartment' => $newapartment ] );
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show( Apartment $apartment )
    {
        $sponsors = Sponsor::all();
        $currentDate = Carbon::now(+2)->format('Y-m-d - H:i:s');

        if($apartment->user_id != Auth::id()){
            abort('403');
        }

        $raw_sponsor_expiration = $apartment->sponsors()
        ->where('expiration', '>=', $currentDate)
        ->first(['expiration']);
        
        if (isset($raw_sponsor_expiration['expiration'])) {
            $sponsor_expiration = Carbon::parse($raw_sponsor_expiration['expiration'])->format('d-m-Y - H:i');
            $apartment->sponsor_expiration = $sponsor_expiration;
        }
        else{
            $sponsor_expiration  = null; 
        }

        return view('admin.apartments.show', compact('sponsors', 'apartment','sponsor_expiration'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit( Apartment $apartment )
    {
        if($apartment->user_id != Auth::id()){
            abort('403');
        }
        $services = Service::all();
        return view('admin.apartments.edit', compact('apartment', 'services'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Apartment $apartment)
    {

        $validation = $this->validation;
        $validation['title'] = 'required|string|max:100|unique:apartments,title,' . $apartment->id;

        $request->validate($validation);

        $data = $request->all();
        
        if ( isset($data['image']) ) {
            $data['image'] = Storage::disk('public')->put('images', $data['image']);
        }

        $data['visible'] = !isset( $data['visible'] ) ? 0 : 1;


        // Generazione dello slug univoco
        do{
            $randomNumSlug = "-".rand(0, 100000000);
            $slugTmp = Str::slug( $data['title'], '-' ).$randomNumSlug;
        }
        while( Apartment::where('slug', $slugTmp)->first() );

        $data['slug'] = $slugTmp;
        $data['user_id'] = Auth::id();

        $apartment->update($data);

        if ( isset($data['services']) ) {
            $apartment->services()->sync( $data['services'] );
        }

        return redirect()
                ->route( 'admin.apartments.show', [ 'apartment' => $apartment ] )
                ->with('message', $apartment->title . 'è stato modificato');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy( Apartment $apartment )
    {

        if( $apartment->user_id != Auth::id() ) {
            abort('403');
        }
        $apartment->delete();

        $apartment->services()->detach();
        $apartment->sponsors()->detach();

        return redirect()
                ->route('admin.apartments.index')
                ->with('message', $apartment->title . 'è stato eliminato');
    }

    public function destroyMessage($id){
        
        $message = Message::find($id);
        
        $apartment = Apartment::find($message->apartment_id);
        
        if( $apartment->user_id != Auth::id() ) {
            abort('403');
        }

        $message->delete();

    }

    public function messages( Apartment $apartment )
    {

        if( $apartment->user_id != Auth::id() ) {
            abort('403');
        }

        $messages = $apartment->messages()->orderBy('created_at', 'desc')->get();
        foreach ( $messages as $message ) {
            $createdAt = Carbon::parse( $message['created_at'] )->format('d/m/Y');
            $message->date = $createdAt;
        }

        return view('admin.apartments.messages', compact('apartment', 'messages'));
    }
}

app/Http/Controllers/Api/ApartmentController.php
<?php

namespace App\Http\Controllers\Api;

use App\Apartment;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Carbon\Carbon;
use Hamcrest\Type\IsNumeric;
use Illuminate\Support\Facades\Auth;

class ApartmentController extends Controller
{
    public function search(Request $request){
        $data = $request->all();
        $request->validate([
            'rooms' => 'numeric | max: 127',
            'bathrooms' => 'numeric | max: 127',
            'beds' => 'numeric | max: 127',
            'mq' => 'numeric | max: 3000',
            'radius' => 'numeric | max: 20038'
        ]);

        $lat = $data['lat'];
        $long = $data['long'];
        $radius_km = 20;
        $rooms = $data['rooms'];
        $bathrooms = $data['bathrooms'];
        $beds = $data['beds'];
        $mq = $data['mq'];
        $toDelete = [];

        if ( isset($data['services']) ) {
            $services = $data['services'];
        }

        if ( isset($data['radius']) ) {
            $radius_km = $data['radius'];
        }
        
        $apartments = Apartment::selectRaw("* , ( 6371 * acos( cos( radians($lat) ) * cos( radians( `lat` ) ) * cos( radians( `long` ) - radians($long) ) + sin( radians($lat) ) * sin( radians( `lat` ) ) ) ) AS distance")
        ->where('rooms', '>=', $rooms)
        ->where('bathrooms', '>=', $bathrooms)
        ->where('beds', '>=', $beds)
        ->where('mq', '>=', $mq)
        ->where('visible', '=', true)
        ->having( 'distance', '<', $radius_km )
        ->orderBy('distance', 'asc' )
        ->get();
        if ( isset($data['services']) ) {
            foreach( $apartments as $index=>$apartment ) {
                $apArrServices = [];
                $apartment->route = route('ui.apartments.show', ['slug' => $apartment->slug]);
                $apartment->image = asset( 'storage/'.$apartment->image );
                $apartment->services;
                $apServices = $apartment->services()->get();
                foreach( $apServices as $apService ) {
                    $apArrServices[] = $apService->id;
                }
                foreach( $services as $service ) {
                    if ( !in_array( $service, $apArrServices ) ) {
                        $toDelete[] = $index;
                    }
                }
            }
            foreach ( $toDelete as $index ) {
                $apartments->forget($index);
            }
        } else {
            foreach( $apartments as $apartment ) {
                $apartment->route = route('ui.apartments.show', ['slug' => $apartment->slug]);
                $apartment->image = asset( 'storage/'.$apartment->image );
                $apartment->services;
            }
        }

        $sorted = $apartments->sortByDesc(function ($apartment) {
            $currentDate = Carbon::now();
            $sponsorColl = $apartment->sponsors()->where('expiration', '>=', $currentDate)->get();
            $sponsor = $sponsorColl->first();
            // L' appartamento non ha sponsor
            if ( $sponsor === null ) {
                return 0;
            }
            // L' appartamento ha sponsor
            $apartment->sponsors;
            if ( $sponsorColl->firstWhere('name', 'Silver') ) {
                return 1;
            } else if ( $sponsorColl->firstWhere('name', 'Gold') ) {
                return 2;
            } else if ( $sponsorColl->firstWhere('name', 'Platinum') ) {
                return 3;
            }
        });
        $apartments = $sorted->values()->all();

        return response()->json($apartments);
    }

    // Api per restituire lat e long alla ui e ur show

    public function apartment($id) {
        
        if ( is_numeric($id) ) {
            $apartment = Apartment::find($id);
        } else {
            $apartment = Apartment::where('slug', $id)->first();
        }

        return response()->json($apartment);
    }

    // Api per le visite tot.

    public function apartmentViews(Apartment $apartment) {
        
        $currentYear = Carbon::now()->format('Y');
        $monthlyViews = [];
        for ( $i = 1; $i <= 12; $i++ ) {
            if ( $i < 10 ) {
                $monthlyViews[$i - 1] = $apartment->views()->whereYear('created_at', $currentYear)->whereMonth('created_at', '0'.$i)->count();
            } else {
                $monthlyViews[$i - 1] = $apartment->views()->whereYear('created_at', $currentYear)->whereMonth('created_at', $i)->count();
            }
        }

        return response($monthlyViews);
    }

    // Api per i messaggi tot.

    public function apartmentMessages(Apartment $apartment) {
        
        $currentYear = Carbon::now()->format('Y');
        $monthlyMessages = [];
        for ( $i = 1; $i <= 12; $i++ ) {
            if ( $i < 10 ) {
                $monthlyMessages[$i - 1] = $apartment->messages()->whereYear('created_at', $currentYear)->whereMonth('created_at', '0'.$i)->count();
            } else {
                $monthlyMessages[$i - 1] = $apartment->messages()->whereYear('created_at', $currentYear)->whereMonth('created_at', $i)->count();
            }
        }

        return response($monthlyMessages);
    }

    // Api che restituisce tutti i messagi dell' appartamento

    public function messagesJson(Apartment $apartment) {

        $messages = $apartment->messages()->orderBy('created_at', 'desc')->get();
        foreach ( $messages as $message ) {
            $createdAt = Carbon::parse( $message['created_at'] )->format('d/m/Y');
            $message->date = $createdAt;
        }

        return response()->json($messages);
    }
}

resources/views/admin/apartments/create.blade.php
@extends('layouts.base-box')

@section('pageTitle')
    BoolBnb - Aggiungi struttura
@endsection

@section('mainTitle')
    Aggiungi un nuovo appartamento
@endsection

@section('MainContent')
    <!-- stampo, se ci sono, lista di errori -->
    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <!-- /stampo, se ci sono, lista di errori -->

    <form id="vue-app" action="{{route('admin.apartments.store')}}" method="POST" class="myForm" enctype="multipart/form-data">
        @method('POST')
        @csrf
        <!-- titolo -->
        <div class="form-group input__title">
            <label for="title">Nome</label>
            <input type="text" class="form-control" id="title" name="title" placeholder="Inserisci nome dell’appartamento" value="{{ old('title') }}" required>
        </div>
        <!-- / titolo -->

        <!-- descrizione -->
        <div class="form-group">
            <label for="description">Descrizione</label>
            <textarea class="form-control" name="description" id="description" rows="10" placeholder="Inserisci descrizione" required>{{ old('description') }}</textarea>
        </div>
        <!-- / descrizione -->

        <div class="inlineInput numericInput multiple-inline">
            <!-- mq -->
            <div class="form-group">
                <label for="mq">Superficie</label>
                <input type="mq" class="form-control" id="mq" name="mq" placeholder="25" value="{{ old('mq') }}" required>
            </div>
            <!-- / mq -->

            <!-- rooms -->
            <div class="form-group">
                <label for="rooms">N. stanze</label>
                <input type="rooms" class="form-control" id="rooms" name="rooms" placeholder="1" value="{{ old('rooms') }}" required>
            </div>
            <!-- / rooms -->

            <!-- beds -->
            <div class="form-group">
                <label for="beds">N. posti letto</label>
                <input type="text" class="form-control" id="beds" name="beds" value="{{ old('beds') }}" placeholder="1" required>
            </div>
            <!-- / beds -->

            <!-- bathroom -->
            <div class="form-group">
                <label for="bathroom">N. bagni</label>
                <input type="bathroom" class="form-control" id="bathroom" name="bathrooms" placeholder="1" value="{{ old('bathrooms') }}" required>
            </div>
            <!-- / bathroom -->
        </div>
        

        <!-- image -->
        <div class="form-group upload-wrapper">
            <label for="image">Carica un immagine</label>
            <input type="file" class="form-control-file upload-image" id="image" name="image">
        </div>
        <!-- / image -->

        <h3>Posizione</h3>
        <div class="inlineInput">
            <!-- address -->
            <div class="form-group input__address">
                <label for="address">Indirizzo (via/piazza, n° civico/interno, CAP)</label>
                <input type="address" class="form-control" id="address" name="address" placeholder="Es: Via Canova, 22/1, 50142" v-on:input=" city !== '' ? geolocate() : ''" v-model="address" value="{{ old('address') }}" required>
            </div>
            <!-- / address -->

            <!-- city -->
            <div class="form-group input__city">
                <label for="city">Città</label>
                <input type="city" class="form-control" id="city" name="city" placeholder="Inserisci città" v-on:input=" city !== '' ? geolocate() : ''" v-model="city" value="{{ old('city') }}" required>
            </div>
            <!-- / city -->
        </div>

        <!-- lat -->
        <div class="form-group">
            <label for="lat">Latitudine</label>
            <input type="lat" class="form-control" readonly id="lat" name="lat" placeholder="Generazione automatica" v-model="lat" value="{{ old('lat') }}" required>
        </div>
        <!-- / lat -->

        <!-- long -->
        <div class="form-group">
            <label for="long">Longitudine</label>
            <input type="long" class="form-control" id="long" readonly name="long" placeholder="Generazione automatica" v-model="long" value="{{ old('long') }}" required>
        </div>
        <!-- / long -->

        <!-- service -->
        <h3>Servizi</h3>
        <div class="services__wrapper">
            @foreach ($services as $service)
                <div class="form-check services">
                    <label class="form-check-label" for="{{ $service->name }}">{{ $service->name }}
                        <input class="form-check-input" type="checkbox" value="{{ $service->id }}" id="{{ $service->name }}" name="services[]" {{ in_array($service->id, old('services', [])) ? 'checked' : '' }}>
                        <span class="checkmark"></span>
                    </label>
                </div>
            @endforeach
        </div>
        <!-- /service --> 

        <!-- visible -->
        <div class="form-check checkVisible">
            <label class="form-check-label" for="visible">Visibile</label>
            <input class="form-check-input" type="checkbox" id="visible" name="visible" value="1" {{ old('visible') ? 'checked' : '' }}>
            <span class="toogle"></span>
        </div>
        <!-- /visible -->

        <div class="text-right">
            <button type="submit" class="my-btn my-btn-primary submit">Aggiungi appartamento</button>
        </div>
    </form>
@endsection

@section('script')
<script src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.21.1/axios.min.js" integrity="sha512-bZS47S7sPOxkjU/4Bt0zrhEtWx0y0CRkhEp8IckzK+ltifIIE9EMIMTuT/mEzoIMewUINruDBIR/jJnbguonqQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="https://cdn.jsdelivr.net/npm/vue@2.6.14/dist/vue.js"></script>
    <script src="{{ asset('js/ur-create-edit.js') }}"></script>
@endsection

resources/views/admin/apartments/edit.blade.php
@extends('layouts.base-box')

@section('pageTitle')
    BoolBnb - Modifica struttura
@endsection

@section('mainTitle')
    Modifica appartamento
@endsection

@section('MainContent')
    <!-- stampo, se ci sono, lista di errori -->
    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <!-- /stampo, se ci sono, lista di errori -->

    <form action="{{route('admin.apartments.update', ['apartment' => $apartment->id])}}" method="POST" class="myForm" enctype="multipart/form-data"  method="POST">
        @method('PUT')
        @csrf
        <!-- titolo -->
        <div class="form-group input__title">
            <label for="title">Nome</label>
            <input type="text" class="form-control" id="title" name="title" placeholder="Inserisci nome dell’appartamento" value="{{ old('title', $apartment->title) }}">
        </div>
        <!-- / titolo -->

        <!-- descrizione -->
        <div class="form-group">
            <label for="description">Descrizione</label>
            <textarea class="form-control" name="description" id="description" rows="10" placeholder="Inserisci descrizione">{{ old('description', $apartment->description) }}</textarea>
        </div>
        <!-- / descrizione -->

        <div class="inlineInput numericInput multiple-inline">
            <!-- mq -->
            <div class="form-group">
                <label for="mq">Superficie</label>
                <input type="mq" class="form-control" id="mq" name="mq" placeholder="25" value="{{ old('mq', $apartment->mq) }}">
            </div>
            <!-- / mq -->

            <!-- rooms -->
            <div class="form-group">
                <label for="rooms">N. stanze</label>
                <input type="rooms" class="form-control" id="rooms" name="rooms" placeholder="1" value="{{ old('rooms', $apartment->rooms) }}">
            </div>
            <!-- / rooms -->

            <!-- beds -->
            <div class="form-group">
                <label for="beds">N. posti letto</label>
                <input type="text" class="form-control" id="beds" name="beds" value="{{ old('beds', $apartment->beds) }}" placeholder="1">
            </div>
            <!-- / beds -->

            <!-- bathroom -->
            <div class="form-group">
                <label for="bathroom">N. bagni</label>
                <input type="bathroom" class="form-control" id="bathroom" name="bathrooms" placeholder="1" value="{{ old('bathrooms', $apartment->bathrooms) }}">
            </div>
            <!-- / bathroom -->
        </div>
        

        <!-- image -->
        <div class="form-group upload-wrapper">
            <label for="image">Carica un immagine</label>
            <input type="file" class="form-control-file upload-image" id="image" name="image" {{ old('image', $apartment->image) }}>
        </div>
        <!-- / image -->

        <h3>Posizione</h3>
        <div class="inlineInput">
            <!-- address -->
            <div class="form-group input__address">
                <label for="address">Indirizzo</label>
                <input type="address" class="form-control" id="address" name="address" placeholder="Inserisci indirizzo" v-on:input=" city !== '' ? geolocate() : ''" v-model="address" value="{{ old('address', $apartment->address) }}">
            </div>
            <!-- / address -->

            <!-- city -->
            <div class="form-group input__city">
                <label for="city">Città</label>
                <input type="city" class="form-control" id="city" name="city" placeholder="Inserisci città" v-on:input=" city !== '' ? geolocate() : ''" v-model="city" value="{{ old('city', $apartment->city) }}">
            </div>
            <!-- / city -->
        </div>

        <!-- lat -->
        <div class="form-group">
            <label for="lat">Latitudine</label>
            <input type="lat" class="form-control" id="lat" name="lat" placeholder="Generazione automatica" v-model="lat" value="{{ old('lat', $apartment->lat) }}">
        </div>
        <!-- / lat -->

        <!-- long -->
        <div class="form-group">
            <label for="long">Longitudine</label>
            <input type="long" class="form-control" id="long" name="long" placeholder="Generazione automatica" v-model="long" value="{{ old('long', $apartment->long) }}">
        </div>
        <!-- / long -->

        <!-- service -->
        <h3>Servizi</h3>
        <div class="services__wrapper">
            @foreach ($services as $service)
                <div class="form-check services">
                    <label class="form-check-label" for="{{ $service->name }}">{{ $service->name }}
                        <input class="form-check-input" type="checkbox" value="{{ old('id',$service->id) }}" id="{{ $service->name }}" name="services[]" {{ old('name', $apartment->services->contains($service)) ? 'checked' : '' }}>
                        <span class="checkmark"></span>
                    </label>
                </div>
            @endforeach
        </div>
        <!-- /service --> 

        <!-- visible -->
        <div class="form-check checkVisible">
            <label class="form-check-label" for="visible">Visibile</label>
            <input class="form-check-input" type="checkbox" id="visible" name="visible" value="1" {{ old('visible', $apartment->visible) ? 'checked' : '' }}>
            <span class="toogle"></span>
        </div>
        <!-- /visible -->

        <div class="text-right">
            <button type="submit" class="my-btn my-btn-primary submit">Modifica appartamento</button>
        </div>
    </form>
@endsection

@section('script')
    
@endsection

resources/views/admin/apartments/index.blade.php
@extends('layouts.base-box')

@section('pageTitle')
    BoolBnb - Dashboard
@endsection

@section('mainTitle')
    I miei appartamenti

    @section('fixedElement')
        <div class="add-btn-wrp">
            <a href="{{route('admin.apartments.create')}}" class="my-btn my-btn-primary add_button"> <i class="fas fa-plus"></i></a>
        </div>
    @endsection
@endsection


@section('MainContent')
    <div class="dash-wrapper">

        @foreach ($apartments as $apartment)
            <div class="dash__card">
                <a href="{{ route('admin.apartments.show', ['apartment' => $apartment->id ] ) }}">
                    <!-- card top -->
                    <div class="img__wrapper">
                        <img src="{{asset('storage/'.$apartment['image'])}}" alt="Immagine appartamento">
                    </div>
                    <!-- / card top -->
                    <!-- card bottom -->
                    <div class="card__caption">
                        <h4>{{$apartment['title']}}</h4>
                        <p class="card__caption__desc">{{$apartment['description']}}</p>
                    </div>
                    <!-- card bottom -->
                </a>
            </div>
        @endforeach 
    </div>
@endsection