routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/////////////////////////////////////////////////////////////////////////////////////////////////

// AREA PUBBLICA
Route::prefix('/')->namespace('UI')->group(function () {
    Route::get('', 'BnbController@index')->name('welcome');
    Route::get('search', 'BnbController@search')->name('search');
    Route::get('apartments', 'BnbController@search')->name('ui.apartments.all');
    Route::get('apartments/{slug}', 'BnbController@show')->name('ui.apartments.show');
    Route::get('apartments/{slug}/message', 'BnbController@sendMessage')->name('ui.apartments.message');
});

Auth::routes();

/////////////////////////////////////////////////////////////////////////////////////////////////

// AREA PRIVATA
Route::prefix('admin')->name('admin.')->namespace('ADMIN')->middleware('auth')->group(function () {
    Route::resource('apartments', 'ApartmentController');
    Route::get('messages/delete/{id}', 'ApartmentController@destroyMessage');
    Route::get('apartments/{apartment}/messages', 'ApartmentController@messages')->name('apartments.messages');
});

Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');

/////////////////////////////////////////////////////////////////////////////////////////////////

// BRAINTREE - TRANSAZIONI

Route::prefix('/admin/')->namespace('Transactions')->group(function () {
    Route::get('apartments/{apartment}/payment', 'PaymentController@form')->name('payment.form');
    Route::get('apartments/payment/process', 'PaymentController@process')->name('payment.process');
    Route::get('apartments/{apartment}/payment/success', 'PaymentController@success')->name('payment.success');
    Route::get('apartments/{apartment}/payment/error', 'PaymentController@error')->name('payment.error');

});

/////////////////////////////////////////////////////////////////////////////////////////////////

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>


    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>


    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">
    <!-- favicon -->
    <link rel="shortcut icon" href="{{ asset('img/favicon.ico') }}">
    <!-- Styles -->
    @yield('styles')
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
       
    
        <header>
            <div class="container-fluid">
                <div class="row flex-center">
                    <div class="col-2">
                        <a href="{{ route('welcome') }}" id="logo"><img src="{{ asset('img/logo-name.png') }}" alt="logo"></a>
                    </div>
                </div>
            </div>
        </header>
            
        <main class="py-4">
            @yield('content')
        </main>
    </div>
    @yield('script')
</body>
</html>

resources/views/layouts/base-box.blade.php
@extends('layouts.base')

@section('mainLay')
    <div class="main__box box-shadow px-0">
        <div class="ur-wrapper">
            <div class="titlewrapper">
                <h2 class="ur-main__title">@yield('mainTitle')</h2>
                @yield('fixedElement')
            </div>

            @yield('MainContent')
        </div>
    </div>
@endsection

resources/views/layouts/base-empty.blade.php
@extends('layouts.base')

@section('mainLay')
@endsection

resources/views/layouts/base.blade.php
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        
        <!-- yeld: nome pagina -->
        <title>@yield('pageTitle')</title>

        <!-- google-font -->
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600&display=swap" rel="stylesheet">
        <!-- / google-font -->
        <!-- favicon -->
        <link rel="shortcut icon" href="{{ asset('img/favicon.ico') }}">
        <!-- style  -->
        @yield('styles')
        <link rel="stylesheet"  href="{{ asset('css/app.css') }}">
        <!-- / style  -->
    </head>
    <body>
        <div id="root">
            <header>
                <div class="container-fluid">
                    <div class="row flex-center">
                        <div class="col-2">
                            <a href="{{ route('welcome') }}" id="logo"><img src="{{ asset('img/logo-name.png') }}" alt="logo"></a>
                        </div>
                        <div class="col-10 text-right">
                            @if (Route::has('login'))
                                <div>
                                    @auth
                                        <a href="{{ route('admin.apartments.index') }}" class="my-btn my-btn-secondary align-bottom"><i class="fas fa-home"></i><span class="d-none d-md-inline-block">Dashboard</span></a>
                                        <a href="/logout" class="my-btn my-btn-primary"><i class="fas fa-sign-out-alt"></i><span class="d-none d-md-inline-block">Log-out</span></a>                        
                                    @else
                                        <a href="{{ route('login') }}" class="my-btn my-btn-primary"><i class="fas fa-sign-out-alt"></i><span class="d-none d-md-inline-block">Log-in</span></a>                        
                                    @if (Route::has('register'))
                                        <a href="{{ route('register') }}" class="my-btn my-btn-primary"><i class="fas fa-sign-in-alt"></i><span class="d-none d-md-inline-block">Registrati</span></a>
                                    @endif
                                    @endauth
                                </div>
                            @endif
                        </div>
                    </div>
                </div>
            </header>
            <main>
                <div class="container">
                    @yield('mainLay')
                </div>
            </main>
            <footer>
                <div class="container-fluid">
                    <div class="row flex-center">
                        <div class="col-6">
                            <a href="{{ route('admin.apartments.index') }}" id="logo"> © 2021 Boolbnb, Inc.</a>
                        </div>
                        <div class="col-6 text-right social-list">
                            <a href="https://www.facebook.com/AirbnbItalia" id="logo"><i class="fab fa-facebook-f"></i></a>
                            <a href="https://www.instagram.com/airbnb/" id="logo"><i class="fab fa-instagram"></i></i></a>
                            <a href="https://twitter.com/airbnb_it" id="logo"><i class="fab fa-twitter"></i></i></a>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
        @yield('script')
    </body>
</html>

resources/views/layouts/email-base.blade.php
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <!-- yeld: nome pagina -->
        <title>@yield('pageTitle')</title>

        <!-- google-font -->
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600&display=swap" rel="stylesheet">
        <!-- / google-font -->

        <!-- style  -->
        @yield('styles')
        <link rel="stylesheet"  href="{{ asset('css/app.css') }}">
        <!-- / style  -->
    </head>
    <body>
        <div id="root">
            <header>
                <div class="container-fluid">
                    <div class="row flex-center">
                        <div class="col-2">
                            <a href="{{ route('welcome') }}" id="logo"><i class="fab fa-airbnb"></i></a>
                        </div>
                        <div class="col-10 text-right">
                                <a href="{{ route('login') }}" class="my-btn my-btn-primary"><i class="fas fa-sign-out-alt"></i><span class="d-none d-md-inline-block">Log-in</span></a>
                        </div>
                    </div>
                </div>
            </header>
            <main>
                <div class="container">
                    @yield('mainLay')
                </div>
            </main>
            <footer>
                <div class="container-fluid">
                    <div class="row flex-center">
                        <div class="col-6">
                            <a href="{{ route('admin.apartments.index') }}" id="logo"> © 2021 Boolbnb, Inc.</a>
                        </div>
                        <div class="col-6 text-right social-list">
                            <a href="https://www.facebook.com/AirbnbItalia" id="logo"><i class="fab fa-facebook-f"></i></a>
                            <a href="https://www.instagram.com/airbnb/" id="logo"><i class="fab fa-instagram"></i></i></a>
                            <a href="https://twitter.com/airbnb_it" id="logo"><i class="fab fa-twitter"></i></i></a>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
        @yield('script')
    </body>
</html>

resources/views/layouts/email-box.blade.php
@extends('layouts.email-base')

@section('mainLay')
    <div class="main__box box-shadow px-0">
        <div class="ur-wrapper">
            <div class="titlewrapper">
                <h2 class="ur-main__title">@yield('mainTitle')</h2>
                @yield('fixedElement')
            </div>

            @yield('MainContent')
        </div>
    </div>
@endsection